snippet_support = false
verbosity = 2

[server]
timeout = 1800 # seconds = 30 minutes

[language.c_cpp]
filetypes = ["c", "cpp"]
roots = [".ccls-root", ".ccls", "compile_commands.json"]
command = "ccls"
args = ["--init={\"completion\":{\"detailedLabel\":false}}"]

# [language.cmake]
# filetypes= ["cmake"]
# command= "cmake-language-server"
# roots= [ "build/" ]
# buildDirectory=["build"]

[language.python]
filetypes = ["py"]
roots = ["requirements.txt", "setup.py", ".git", ".hg"]
command = "pyls"

[language.sh]
filetypes = ["sh"]
command = "bash-language-server"
roots = ["."]
