verbosity = 2

[server]
timeout = 1800 # seconds = 30 minutes

[language.c_cpp]
filetypes = ["c", "cpp"]
roots = [".cquery", "compile_commands.json"]
command = "cquery"
args = ["--log-file=/tmp/cq.log", "--init={\"cacheDirectory\": \"/home/charles/.cache/cquery\"}"]
