snippet_support = false
verbosity = 2

[server]
timeout = 1800 # seconds = 30 minutes

[language.c_cpp]
filetypes = ["c", "cpp"]
roots = [".ccls-root", ".ccls", "build/compile_commands.json", "compile_commands.json"]
command = "ccls"
# args = ["--log-file=/tmp/cq.log", "--init={\"cacheDirectory\": \"/home/charles/.cache/cquery\"}"]
args = ["--init={\"completion\":{\"detailedLabel\":false}}"]
